### ISSUE TITLE
terminal插件快捷键失效

### ISSUE THREAD

**Issue by yyBeta** [lyfeyaj/sublime-text-imfix#18]
如题，不知道其它插件的快捷键会不会失效

**Comment by lyfeyaj** [comment]
是无法用 subl 命令启动么?

**Comment by yyBeta** [comment]
不是，terminal是一个sublime插件，可以直接用terminal打开当前操作文件的目录或工程目录。发现只要加了preload就会失效，但其它插件都没影响，给插件开发者反馈也没有解决，自己弄了很久都没有找到解决方法，无奈中文输入与它不能兼得，中文输入必须要，只得换了个类似但不那么好用的替代品。

**Comment by peterfyj** [comment]
@yyBeta  这个问题是因为`LD_PRELOAD`环境变量会传给gnome-terminal，导致gtk+2和gtk+3的冲突。应该在调用gnome-terminal时取消该环境变量。请参考我的[pull request](https://github.com/wbond/sublime_terminal/pull/150)。下一版Terminal应该就会包含这个pull request了。

**Comment by yyBeta** [comment]
非常感谢！
