### ISSUE TITLE
sublime 3126 没有成功

### ISSUE THREAD

**Issue by skyday2012** [lyfeyaj/sublime-text-imfix#28]
按照教程来的，用的是root权限也不行，无法输入中文，是新版本的问题吗？？

**Comment by lyfeyaj** [comment]
脚本仅支持 ubuntu, 部分情况下, 需手动在系统设置中指定输入法为 fcitx

**Comment by skyday2012** [comment]
我用的是Ubuntu16.04 lts 输入法是搜狗输入法，是不是和这个有关系呢？？

**Comment by lyfeyaj** [comment]
目前只支持 fcitx 这款输入法

**Comment by skyday2012** [comment]
哦，明白了。谢谢！！
