### ISSUE TITLE
输入法窗口不跟框

### ISSUE THREAD

**Issue by CigarZh** [lyfeyaj/sublime-text-imfix#29]
输入法窗口不跟框，永远悬浮在左下角。
看到前辈的输入法演示是跟框的有什么解决的思路吗？

**Comment by lyfeyaj** [comment]
这个补丁并不能解决输入法跟随的问题

**Comment by lyfeyaj** [comment]
输入法跟随的问题已修复, 拉取最新修复脚本, 并重新运行脚本 `./sublime-imfix` 后重新启动 sublime 即可修复
