### ISSUE TITLE
请问你的中文输入法是如何做到跟随光标的？

### ISSUE THREAD

**Issue by xiao27** [lyfeyaj/sublime-text-imfix#30]
我用的是Ubuntu16.04 LTS 搜狗输入法，运行脚本之后能在sublime 3中输入中文，但输入法的候选框一直在屏幕左下角。不能想项目截图一样的跟随

**Comment by lyfeyaj** [comment]
这个脚本并不能解决输入法跟随的问题

**Comment by xiao27** [comment]
谢谢！我只是看到你的配图里面的输入法是跟随的，才发问。谢谢，我已经解决了中文输入的问题。

Raspberry's iPhone

在 2017年2月23日，19:20，lyfeyaj <notifications@github.com<mailto:notifications@github.com>> 写道：


这个脚本并不能解决输入法跟随的问题

**Comment by lyfeyaj** [comment]
😄

**Comment by lyfeyaj** [comment]
输入法跟随的问题已修复, 拉取最新修复脚本, 并重新运行脚本 `./sublime-imfix` 后重新启动 sublime 即可修复
