### ISSUE TITLE
不清楚是不是这个项目导致了搜狗输入法的问题。

### ISSUE THREAD

**Issue by luyang93** [lyfeyaj/sublime-text-imfix#31]
目前搜狗输入法无法正常使用。
~$ sogou-qimpanel
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
~$ No LSB modules are available.
No LSB modules are available.
(WARN-19143 /build/fcitx-PSoVA1/fcitx-4.2.9.1/src/lib/fcitx-config/fcitx-config.c:922) Invalid Entry: line 148 missing '='

**Comment by lyfeyaj** [comment]
从报错看起来，并不是这个项目导致的，可以尝试重新安装搜狗输入法
