### ISSUE TITLE
安装成功后，可以输入中文，但是一写MD背景就变白

### ISSUE THREAD

**Issue by IdiotYcw** [lyfeyaj/sublime-text-imfix#32]
Ubuntu 14.04 LTS
ST3
右下角切换成其他文件编写方式，背景都是我设置的黑色
但一切换成Markdown就这样，也无法设置
![screenshot from 2017-03-16 13 40 53](https://cloud.githubusercontent.com/assets/19967761/23983302/3888a544-0a4e-11e7-9495-87b4cf48bf67.png)

**Comment by NarsiHuang** [comment]
请问这个问题怎么解决的？
