### ISSUE TITLE
搜狗输入法显示的位置不适合

### ISSUE THREAD

**Issue by cnzero** [lyfeyaj/sublime-text-imfix#33]
首先，非常感谢楼主的解决方案，目前尝试了介绍的方法，已经能够正确在Sublime 3内正确输入中文。
目前还有一点儿小的问题，就是在输入中文时，输入法显示的位置并不十分合适，无论在哪里输入一直显示在左下角的位置。
所以，提一个issue，^_^

**Comment by lyfeyaj** [comment]
Identical to #15 #29 #30

**Comment by cnzero** [comment]
Thank you all the same. ^_^

**Comment by lyfeyaj** [comment]
输入法跟随的问题已修复, 拉取最新修复脚本, 并重新运行脚本 `./sublime-imfix` 后重新启动 sublime 即可修复
