### ISSUE TITLE
安装好后预览markdown文件会出现乱码

### ISSUE THREAD

**Issue by wuzy361** [lyfeyaj/sublime-text-imfix#35]
我之前有markdown插件，右键markdown文件open in browser预览，会出现乱码，之前是好的。能提供解决方法吗，或者卸载方法也行。

**Comment by lyfeyaj** [comment]
拉取最新的脚本, 重新运行 `./sublime-imfix`, 看是否可以解决你的问题. 如果不行, 就注释或删掉 `/usr/bin/subl` 文件里面的 `export LD_PRELOAD=/opt/sublime_text/libsublime-imfix.so` 这一行即可
