### ISSUE TITLE
请问输入框不跟随光标，怎么解决？

### ISSUE THREAD

**Issue by fengqiaozhu** [lyfeyaj/sublime-text-imfix#40]
能够输入中文，但是输入框，不跟随光标，怎么弄？？

**Comment by lyfeyaj** [comment]
This is a duplicate of #15 #29 #30 #33 though, closing this one

**Comment by lyfeyaj** [comment]
输入法跟随的问题已修复, 重新运行脚本 `./sublime-imfix` 后重新启动 sublime 即可修复

**Comment by fengqiaozhu** [comment]
谢谢🙏




发自网易邮箱大师
在2017年08月08日 18:24，lyfeyaj 写道：

输入法跟随的问题已修复, 重新运行脚本 ./sublime-imfix 后重新启动 sublime 即可修复
