### ISSUE TITLE
sublime text 图标消失

### ISSUE THREAD

**Issue by ianzhengnan** [lyfeyaj/sublime-text-imfix#41]
安装过这个以后，sublime text 的图标消失了。但是的确可以打中文了！

**Comment by lyfeyaj** [comment]
可以复制 `src/sublime-text.desktop` 到桌面 即可解决

**Comment by watain666** [comment]
安裝後將/usr/share/applications/sublime-text.desktop裡第11行
`Icon=sublime-text`
加上副檔名.png改成
`Icon=sublime-text.png`
存檔後圖示就會正常顯示了。
