### ISSUE TITLE
Fix for fcitx does not work, but fix for xim immodule works for fcitx

### ISSUE THREAD

**Issue by nemo-nullius** [lyfeyaj/sublime-text-imfix#50]
At first, thank you so much for this wonderful fix. 

It is very strange that in my case, after patching this fix, I cannot get it to work. Everytime when I switch to fcitx in sublime text, it will keep switching back to English keyboard again, and I cannot type in any Chinese characters at all. However, after I delete all the lines from 38 to 115 in `sublime-imfix.c` (all the codes concerning fcitx are deleted and xim are left) and then re-compile and use it, this time it works very well. I can type in Chinese characters with fcitx as usual! So I am very confused about the outcome - why codes for fcitx does not work for fcitx but those for xim does work for fcitx in my case?

My environment is as follows:

- OS: ubuntu 14.04 + i3wm/xfce4
- Imput Method: fcitx 4.2.8.5
- Sublime Ver 3.0, Build 3143
- sublime-text-imfix: commit de1cc97 (latest)

Thank you for your help!

**Comment by lyfeyaj** [comment]
Couldn't reproduce ...

**Comment by nemo-nullius** [comment]
It is indeed quite strange... But thank you so much all the same for your help!

By the way, I also find that the behavior of deleting is not correct in sublime with fcitx after patching this fix. Everytime when I press backspace, it deletes the words in sublime rather than those in the input box of fcitx.  This issue seems to be prevalent and seems to have perplexed many people on the internet. Do you know any solution to this problem please?

**Comment by nemo-nullius** [comment]
I have come up with a method to work around this deleting problem. See #46
