### ISSUE TITLE
[enhancement] vintage模式下, 能否做到如fcitx.vim的效果

### ISSUE THREAD

**Issue by huangjj27** [lyfeyaj/sublime-text-imfix#51]
众所周知, 使用`vim`模式进行输入的时候, 当用户退出到`normal`模式状态时, 输入法状态会保留在`insert`模式时的状态, 而原生vim的解决方案时通过插件`fcitx.vim`来自动做切换, 方便了很多用户. 那么, 我们IMFIX是否也可以顺便修补这个问题呢?

**Comment by nemo-nullius** [comment]
@huangjj27 建议用 AcutalVim 这个 package (https://github.com/lunixbochs/ActualVim)，它会调用neovim，如果再在 neovim 里装上 fcitx.vim 插件就会达到你想要的效果。

**Comment by huangjj27** [comment]
@nemo-nullius 确实能够有达到我想要的效果! 谢谢!
