### ISSUE TITLE
Can't open Preferences - Browse Packages

### ISSUE THREAD

**Issue by nemonein** [lyfeyaj/sublime-text-imfix#6]
First, Thank you for your library.
I'm using ubuntu 14.04(64bit), fcitx(actually fcitx-hangul; Korean), sublime-text-3, and sublime-text-imfix.
It works fine, and I can make myself input Korean.

However, I have found out that 'Preferences - Browse Packages' is not openned.
I'm just using Sublime-text, so I don't know about this one well.
I googled, and I have found something that indicates there are some issues on this library.

http://html5beta.com/page/ubuntu-14-04-install-fcitx-sougoupinyin-sublime-text-3-chinese-input-fix.html

I hope you might take a look at this.
Thanks.

**Comment by lyfeyaj** [comment]
Hi can you provide some screenshots that I can help with?
Besides, your problem seems to be something wrong with your installed version of Sublime Text, you can try to re-install sublime text

**Comment by nemonein** [comment]
Thank you for your answer.
I think Sublime Text is ok, since I installed this.
http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb

There are no screen shots I can show you, because there is no response even I clicked the top down menu(Preferences - Browse Packages).
But without preloading the sublime-text-imfix, Preferences - Browse Packages menu works fine. (Nautilus opened.)

**Comment by darfux** [comment]
+1, when running in terminal, the output is:
`(nautilus:4222): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported`

**Comment by lyfeyaj** [comment]
fixed in #19
