### ISSUE TITLE
cannot be preloaded

### ISSUE THREAD

**Issue by jcleng** [lyfeyaj/sublime-text-imfix#65]
OS: Debian
Kernel: i686 Linux 4.9.0-3-686-pae
WM: Mutter(DeepinGala)
CPU: Intel Celeron CPU G530 @ 2.4GHz
GPU: GeForce GT 430
RAM: 600MB / 2002MB

puppy@stretch:~$ subl
ERROR: ld.so: object '/opt/sublime_text/libsublime-imfix.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

启动之后不能输入中文，是i686的原因吗，该如何解决呢

**Comment by UlyC** [comment]
可以参照 @inouetoukyou 提交的pull request  ：https://github.com/lyfeyaj/sublime-text-imfix/pull/61，之后完美解决此问题

**Comment by lyfeyaj** [comment]
Fixed by #61
